### ISSUE TITLE
H43 does not read SD card at all, and cannot boot with SD card inserted

### ISSUE THREAD

**Issue by Voxel3DPrinting** [makerbase-mks/MKS-H43#7]
Hey,
My H43 screen does not read the SD cards for my GCODE files, I am using an MKS SGen L V2, with MKS2209 drivers and configured marlin exactly as the Wiki said..
I also have tried multiple SD cards of different sizes (4-32GB), and formatted them in different ways / cluster sizes.
Note:
If I insert the SD card while the printer is on, it just does not read anything. If I insert the SD card before booting, and the printer boots, the screen just gets slightly dim and does not boot any further.

Edit;
I think I at least got something figured out;
In the marlin V2.0 you provided for the H43, it defaults to "#define SDCARD_CONNECTION LCD" in Configuration.adv. However, If i check the "Pins" file of my main board (MKS Sgen L V2) it says;
"#if SD_CONNECTION_IS(LCD) || SD_CONNECTION_IS(ONBOARD)
  #define SD_DETECT_PIN                    P0_27
  #define SD_SCK_PIN                       P0_07
  #define SD_MISO_PIN                      P0_08
  #define SD_MOSI_PIN                      P0_09"

However, those pins (P0_27, P0,07, P0_08 and P0_09) are located in the EXP-1 connector instead of the AUX connector. (See pinout of MKS SgenL V2; https://github.com/makerbase-mks/MKS-SGEN_L-V2/wiki/Hardware_description#Wiring_Pinout_and_Size) 

I think it has to do something with this and somehow need t change those pins from the EXP-1 connector to the AUX connector which the H43 is connected to. But I cannot figure out how I can do this, does anyone have any ideas?

**Comment by Jontux** [comment]
Same here with an H43 connected to a SKR V1.4 Turbo. SD card does not appear neither with the SD card connected to an H43 nor mainboard.

**Comment by reQu1em00** [comment]
I can now get it working but only with a very small SD card.  128MB worked for me.  No other size will work even though I can update firmware with a larger version.

**Comment by Voxel3DPrinting** [comment]
I modified the Board file and I now can read the Gcode from the onboard SD, but the screen SD does nothing. Contacted MKS via Ali and they said the H43 cannot read Gcode..
Maybe an Idea to put this information somewheere @mks-viva @makerbase-mks ??

**Comment by Jontux** [comment]
I noticed also that Marlin tryes to read the SD card from pins of AUX-2 when the screen is set to MKS H43. Mainboard is SKR 1.4 Turbo.

But ok, I bought the H43 to read the SD card and to control printer but nice to know if it doesn't even read the G-code 😅 I would like to know if it's even possible to do so with some firmware changes 🤔

**Comment by Voxel3DPrinting** [comment]
> I noticed also that Marlin tryes to read the SD card from pins of AUX-2 when the screen is set to MKS H43. Mainboard is SKR 1.4 Turbo.
> 
> But ok, I bought the H43 to read the SD card and to control printer but nice to know if it doesn't even read the G-code 😅 I would like to know if it's even possible to do so with some firmware changes 🤔

Same exact problem here.. I just grinded a slot in my printers case to get acces to the SD slot. I fixed the reading issue by changing the Board pins file and settin gthe SD mode to "ONBOAD"
Maybe this works 4 u to

**Comment by Metalazzo** [comment]
I have the same problem. I cannot boot with a micro sdcard inserted in the H43 LCD (black screen, I suppose it tries to update) or if I plug it after boot, there is no file found. Read perfectly gcode files from E3D main board.
I think it's really stupid coming from MKS. And I don't understand why "it cannot read gcode". Well according to schematic it can. That they don't want to make any effort on the software side, it's an other story.
Finally, I found their lack of support disturbing... For example, you can't have a BLtouch and neopixel plugged on a MKS E3D and H43 out of the box, you need to reassign pins.

**Comment by buiduy6868** [comment]
@Voxel3DPrinting 
Hi bro, have you solve your problem, I got the same issue with my H43+MKS Sgen L V2. I dont know how to do now

**Comment by Voxel3DPrinting** [comment]
It appears the SD on the screen is only ment for updating the H43 screen and not for data transfer.
For the Gcode files you have to use the motherboard SD
